// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_BATCHNORMINFERENCEATTRIBUTESVARIANCEEXT_HIPDNN_DATA_SDK_DATA_OBJECTS_H_
#define FLATBUFFERS_GENERATED_BATCHNORMINFERENCEATTRIBUTESVARIANCEEXT_HIPDNN_DATA_SDK_DATA_OBJECTS_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 9 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

namespace hipdnn_data_sdk {
namespace data_objects {

struct BatchnormInferenceAttributesVarianceExt;
struct BatchnormInferenceAttributesVarianceExtBuilder;
struct BatchnormInferenceAttributesVarianceExtT;

bool operator==(const BatchnormInferenceAttributesVarianceExtT &lhs, const BatchnormInferenceAttributesVarianceExtT &rhs);
bool operator!=(const BatchnormInferenceAttributesVarianceExtT &lhs, const BatchnormInferenceAttributesVarianceExtT &rhs);

struct BatchnormInferenceAttributesVarianceExtT : public ::flatbuffers::NativeTable {
  typedef BatchnormInferenceAttributesVarianceExt TableType;
  int64_t x_tensor_uid = 0;
  int64_t mean_tensor_uid = 0;
  int64_t variance_tensor_uid = 0;
  int64_t scale_tensor_uid = 0;
  int64_t bias_tensor_uid = 0;
  int64_t y_tensor_uid = 0;
  int64_t epsilon_tensor_uid = 0;
};

struct BatchnormInferenceAttributesVarianceExt FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef BatchnormInferenceAttributesVarianceExtT NativeTableType;
  typedef BatchnormInferenceAttributesVarianceExtBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_X_TENSOR_UID = 4,
    VT_MEAN_TENSOR_UID = 6,
    VT_VARIANCE_TENSOR_UID = 8,
    VT_SCALE_TENSOR_UID = 10,
    VT_BIAS_TENSOR_UID = 12,
    VT_Y_TENSOR_UID = 14,
    VT_EPSILON_TENSOR_UID = 16
  };
  int64_t x_tensor_uid() const {
    return GetField<int64_t>(VT_X_TENSOR_UID, 0);
  }
  bool mutate_x_tensor_uid(int64_t _x_tensor_uid = 0) {
    return SetField<int64_t>(VT_X_TENSOR_UID, _x_tensor_uid, 0);
  }
  int64_t mean_tensor_uid() const {
    return GetField<int64_t>(VT_MEAN_TENSOR_UID, 0);
  }
  bool mutate_mean_tensor_uid(int64_t _mean_tensor_uid = 0) {
    return SetField<int64_t>(VT_MEAN_TENSOR_UID, _mean_tensor_uid, 0);
  }
  int64_t variance_tensor_uid() const {
    return GetField<int64_t>(VT_VARIANCE_TENSOR_UID, 0);
  }
  bool mutate_variance_tensor_uid(int64_t _variance_tensor_uid = 0) {
    return SetField<int64_t>(VT_VARIANCE_TENSOR_UID, _variance_tensor_uid, 0);
  }
  int64_t scale_tensor_uid() const {
    return GetField<int64_t>(VT_SCALE_TENSOR_UID, 0);
  }
  bool mutate_scale_tensor_uid(int64_t _scale_tensor_uid = 0) {
    return SetField<int64_t>(VT_SCALE_TENSOR_UID, _scale_tensor_uid, 0);
  }
  int64_t bias_tensor_uid() const {
    return GetField<int64_t>(VT_BIAS_TENSOR_UID, 0);
  }
  bool mutate_bias_tensor_uid(int64_t _bias_tensor_uid = 0) {
    return SetField<int64_t>(VT_BIAS_TENSOR_UID, _bias_tensor_uid, 0);
  }
  int64_t y_tensor_uid() const {
    return GetField<int64_t>(VT_Y_TENSOR_UID, 0);
  }
  bool mutate_y_tensor_uid(int64_t _y_tensor_uid = 0) {
    return SetField<int64_t>(VT_Y_TENSOR_UID, _y_tensor_uid, 0);
  }
  int64_t epsilon_tensor_uid() const {
    return GetField<int64_t>(VT_EPSILON_TENSOR_UID, 0);
  }
  bool mutate_epsilon_tensor_uid(int64_t _epsilon_tensor_uid = 0) {
    return SetField<int64_t>(VT_EPSILON_TENSOR_UID, _epsilon_tensor_uid, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int64_t>(verifier, VT_X_TENSOR_UID, 8) &&
           VerifyField<int64_t>(verifier, VT_MEAN_TENSOR_UID, 8) &&
           VerifyField<int64_t>(verifier, VT_VARIANCE_TENSOR_UID, 8) &&
           VerifyField<int64_t>(verifier, VT_SCALE_TENSOR_UID, 8) &&
           VerifyField<int64_t>(verifier, VT_BIAS_TENSOR_UID, 8) &&
           VerifyField<int64_t>(verifier, VT_Y_TENSOR_UID, 8) &&
           VerifyField<int64_t>(verifier, VT_EPSILON_TENSOR_UID, 8) &&
           verifier.EndTable();
  }
  BatchnormInferenceAttributesVarianceExtT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(BatchnormInferenceAttributesVarianceExtT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<BatchnormInferenceAttributesVarianceExt> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const BatchnormInferenceAttributesVarianceExtT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct BatchnormInferenceAttributesVarianceExtBuilder {
  typedef BatchnormInferenceAttributesVarianceExt Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_x_tensor_uid(int64_t x_tensor_uid) {
    fbb_.AddElement<int64_t>(BatchnormInferenceAttributesVarianceExt::VT_X_TENSOR_UID, x_tensor_uid, 0);
  }
  void add_mean_tensor_uid(int64_t mean_tensor_uid) {
    fbb_.AddElement<int64_t>(BatchnormInferenceAttributesVarianceExt::VT_MEAN_TENSOR_UID, mean_tensor_uid, 0);
  }
  void add_variance_tensor_uid(int64_t variance_tensor_uid) {
    fbb_.AddElement<int64_t>(BatchnormInferenceAttributesVarianceExt::VT_VARIANCE_TENSOR_UID, variance_tensor_uid, 0);
  }
  void add_scale_tensor_uid(int64_t scale_tensor_uid) {
    fbb_.AddElement<int64_t>(BatchnormInferenceAttributesVarianceExt::VT_SCALE_TENSOR_UID, scale_tensor_uid, 0);
  }
  void add_bias_tensor_uid(int64_t bias_tensor_uid) {
    fbb_.AddElement<int64_t>(BatchnormInferenceAttributesVarianceExt::VT_BIAS_TENSOR_UID, bias_tensor_uid, 0);
  }
  void add_y_tensor_uid(int64_t y_tensor_uid) {
    fbb_.AddElement<int64_t>(BatchnormInferenceAttributesVarianceExt::VT_Y_TENSOR_UID, y_tensor_uid, 0);
  }
  void add_epsilon_tensor_uid(int64_t epsilon_tensor_uid) {
    fbb_.AddElement<int64_t>(BatchnormInferenceAttributesVarianceExt::VT_EPSILON_TENSOR_UID, epsilon_tensor_uid, 0);
  }
  explicit BatchnormInferenceAttributesVarianceExtBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<BatchnormInferenceAttributesVarianceExt> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<BatchnormInferenceAttributesVarianceExt>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<BatchnormInferenceAttributesVarianceExt> CreateBatchnormInferenceAttributesVarianceExt(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int64_t x_tensor_uid = 0,
    int64_t mean_tensor_uid = 0,
    int64_t variance_tensor_uid = 0,
    int64_t scale_tensor_uid = 0,
    int64_t bias_tensor_uid = 0,
    int64_t y_tensor_uid = 0,
    int64_t epsilon_tensor_uid = 0) {
  BatchnormInferenceAttributesVarianceExtBuilder builder_(_fbb);
  builder_.add_epsilon_tensor_uid(epsilon_tensor_uid);
  builder_.add_y_tensor_uid(y_tensor_uid);
  builder_.add_bias_tensor_uid(bias_tensor_uid);
  builder_.add_scale_tensor_uid(scale_tensor_uid);
  builder_.add_variance_tensor_uid(variance_tensor_uid);
  builder_.add_mean_tensor_uid(mean_tensor_uid);
  builder_.add_x_tensor_uid(x_tensor_uid);
  return builder_.Finish();
}

::flatbuffers::Offset<BatchnormInferenceAttributesVarianceExt> CreateBatchnormInferenceAttributesVarianceExt(::flatbuffers::FlatBufferBuilder &_fbb, const BatchnormInferenceAttributesVarianceExtT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);


inline bool operator==(const BatchnormInferenceAttributesVarianceExtT &lhs, const BatchnormInferenceAttributesVarianceExtT &rhs) {
  return
      (lhs.x_tensor_uid == rhs.x_tensor_uid) &&
      (lhs.mean_tensor_uid == rhs.mean_tensor_uid) &&
      (lhs.variance_tensor_uid == rhs.variance_tensor_uid) &&
      (lhs.scale_tensor_uid == rhs.scale_tensor_uid) &&
      (lhs.bias_tensor_uid == rhs.bias_tensor_uid) &&
      (lhs.y_tensor_uid == rhs.y_tensor_uid) &&
      (lhs.epsilon_tensor_uid == rhs.epsilon_tensor_uid);
}

inline bool operator!=(const BatchnormInferenceAttributesVarianceExtT &lhs, const BatchnormInferenceAttributesVarianceExtT &rhs) {
    return !(lhs == rhs);
}


inline BatchnormInferenceAttributesVarianceExtT *BatchnormInferenceAttributesVarianceExt::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<BatchnormInferenceAttributesVarianceExtT>(new BatchnormInferenceAttributesVarianceExtT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void BatchnormInferenceAttributesVarianceExt::UnPackTo(BatchnormInferenceAttributesVarianceExtT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = x_tensor_uid(); _o->x_tensor_uid = _e; }
  { auto _e = mean_tensor_uid(); _o->mean_tensor_uid = _e; }
  { auto _e = variance_tensor_uid(); _o->variance_tensor_uid = _e; }
  { auto _e = scale_tensor_uid(); _o->scale_tensor_uid = _e; }
  { auto _e = bias_tensor_uid(); _o->bias_tensor_uid = _e; }
  { auto _e = y_tensor_uid(); _o->y_tensor_uid = _e; }
  { auto _e = epsilon_tensor_uid(); _o->epsilon_tensor_uid = _e; }
}

inline ::flatbuffers::Offset<BatchnormInferenceAttributesVarianceExt> BatchnormInferenceAttributesVarianceExt::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const BatchnormInferenceAttributesVarianceExtT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateBatchnormInferenceAttributesVarianceExt(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<BatchnormInferenceAttributesVarianceExt> CreateBatchnormInferenceAttributesVarianceExt(::flatbuffers::FlatBufferBuilder &_fbb, const BatchnormInferenceAttributesVarianceExtT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const BatchnormInferenceAttributesVarianceExtT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _x_tensor_uid = _o->x_tensor_uid;
  auto _mean_tensor_uid = _o->mean_tensor_uid;
  auto _variance_tensor_uid = _o->variance_tensor_uid;
  auto _scale_tensor_uid = _o->scale_tensor_uid;
  auto _bias_tensor_uid = _o->bias_tensor_uid;
  auto _y_tensor_uid = _o->y_tensor_uid;
  auto _epsilon_tensor_uid = _o->epsilon_tensor_uid;
  return hipdnn_data_sdk::data_objects::CreateBatchnormInferenceAttributesVarianceExt(
      _fbb,
      _x_tensor_uid,
      _mean_tensor_uid,
      _variance_tensor_uid,
      _scale_tensor_uid,
      _bias_tensor_uid,
      _y_tensor_uid,
      _epsilon_tensor_uid);
}

}  // namespace data_objects
}  // namespace hipdnn_data_sdk

#endif  // FLATBUFFERS_GENERATED_BATCHNORMINFERENCEATTRIBUTESVARIANCEEXT_HIPDNN_DATA_SDK_DATA_OBJECTS_H_
